"""Shell function templates for `roost shellinit`.

Generates a wrapper function for `claude` (the upstream CLI) that auto-routes
through `roost exec --auto-refresh -- claude ...`. The wrapper preserves
interactive behaviour (stdin/stdout/stderr inherited via roost exec) and
ctrl+C handling.

Each template is a string with no `{}` interpolation: shells handle their own
arg-passing semantics, so we just emit the right syntax for each.

Wire-up (per shell):

    bash/zsh:    eval "$(roost shellinit)"
    fish:        roost shellinit | source
    pwsh:        roost shellinit | Out-String | Invoke-Expression

The intent is "one line in your shell rc to make every `claude` invocation
go through roost". Calling `roost shellinit --shell <name>` overrides the
auto-detected shell.
"""

from __future__ import annotations

import os
from pathlib import Path

SUPPORTED_SHELLS = ("bash", "zsh", "fish", "pwsh")


_BASH_ZSH_TEMPLATE = """\
# claude-lb shell integration (bash/zsh).
# Generated by `roost shellinit`. Eval into your shell rc.
claude() {
    command roost exec --auto-refresh -- claude "$@"
}
"""

_FISH_TEMPLATE = """\
# claude-lb shell integration (fish).
# Generated by `roost shellinit`. Source into your shell rc.
function claude
    command roost exec --auto-refresh -- claude $argv
end
"""

_PWSH_TEMPLATE = """\
# claude-lb shell integration (PowerShell).
# Generated by `roost shellinit`. Pipe into Invoke-Expression.
function claude {
    & roost exec --auto-refresh -- claude @args
}
"""


def detect_shell() -> str:
    """Best-effort detect the user's shell from $SHELL or $PSModulePath.

    Falls back to `bash` if no signal is found — bash is the safest default
    since the template is also valid zsh.
    """
    shell_env = os.environ.get("SHELL", "")
    if shell_env:
        name = Path(shell_env).name.lower()
        if name == "fish":
            return "fish"
        if name == "zsh":
            return "zsh"
        if "bash" in name:
            return "bash"
    # Windows PowerShell heuristic: PSModulePath is usually set in pwsh.
    # noqa: SIM112 — Windows env-var name is conventionally MixedCase.
    if os.environ.get("PSModulePath"):  # noqa: SIM112
        return "pwsh"
    return "bash"


def template_for(shell: str) -> str:
    """Return the shell-init template for the given shell.

    Raises ValueError for unknown shells; the CLI converts that into an
    EXIT_VALIDATION failure with a list of supported names.
    """
    s = shell.strip().lower()
    if s in ("bash", "zsh"):
        return _BASH_ZSH_TEMPLATE
    if s == "fish":
        return _FISH_TEMPLATE
    if s == "pwsh":
        return _PWSH_TEMPLATE
    raise ValueError(
        f"unknown shell: {shell!r}. Supported: {', '.join(SUPPORTED_SHELLS)}"
    )
